AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Slack で映画を 3 本おすすめする Bot

Globals:
  Function:
    Runtime: python3.9
    Timeout: 10
    MemorySize: 256

Resources:
  # DynamoDB テーブル
  SessionsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: FileChatSessions
      PrimaryKey:
        Name: sessionId
        Type: String

  # HTTP API 定義
  FilmateApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod

  # 1) /filmChatEntry スラッシュコマンド受信用 Lambda
  FilmChatEntryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/filmChatEntry/
      Handler: app.lambda_handler
      Environment:
        Variables:
          SLACK_BOT_TOKEN: '{{resolve:secretsmanager:arn:aws:secretsmanager:ap-northeast-1:088622163445:secret:prod/filmmate/slack-rRHqLA:SecretString:slack_bot_token}}'
          SLACK_SIGNING_SECRET: '{{resolve:secretsmanager:arn:aws:secretsmanager:ap-northeast-1:088622163445:secret:prod/filmmate/slack-rRHqLA:SecretString:slack_signing_secret}}'
          TMDB_KEY: '{{resolve:secretsmanager:arn:aws:secretsmanager:ap-northeast-1:088622163445:secret:prod/filmmate/slack-rRHqLA:SecretString:tmdb_key}}'
          SESSIONS_TABLE: !Ref SessionsTable
          CHAT_HANDLER_NAME: !GetAtt FilmChatFlowFunction.FunctionName
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:ap-northeast-1:088622163445:secret:prod/filmmate/slack-rRHqLA
        - Statement:
            - Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt FilmChatFlowFunction.Arn
      Events:
        SlashCommand:
          Type: HttpApi
          Properties:
            ApiId: !Ref FilmateApi
            Path: /filmChatEntry
            Method: POST

  # 2) 会話フロー実行用 Lambda（内部呼び出し）
  FilmChatFlowFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/filmChatFlow/
      Handler: app.lambda_handler
      Environment:
        Variables:
          SESSIONS_TABLE: !Ref SessionsTable
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:ap-northeast-1:088622163445:secret:prod/filmmate/slack-rRHqLA

  # 3) Events API サブスクリプション受信用 Lambda
  EventsHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/eventsHandler/
      Handler: app.lambda_handler
      Environment:
        Variables:
          SLACK_SIGNING_SECRET: '{{resolve:secretsmanager:arn:aws:secretsmanager:ap-northeast-1:088622163445:secret:prod/filmmate/slack-rRHqLA:SecretString:slack_signing_secret}}'
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: arn:aws:secretsmanager:ap-northeast-1:088622163445:secret:prod/filmmate/slack-rRHqLA
      Events:
        SlackEvents:
          Type: HttpApi
          Properties:
            ApiId: !Ref FilmateApi
            Path: /events
            Method: POST

Outputs:
  HttpApiUrl:
    Description: "Bot の HTTP API ベース URL"
    Value: !Sub "https://${FilmateApi}.execute-api.${AWS::Region}.amazonaws.com/prod"