AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Slack で映画を 3本おすすめする Bot

Globals:
  Function:
    Runtime: python3.9
    Timeout: 10
    MemorySize: 256
    Environment:
      Variables:
        SLACK_SECRET_ID: arn:aws:secretsmanager:ap-northeast-1:088622163445:secret:prod/filmmate/slack-rRHqLA
        SESSIONS_TABLE: !Ref FilmChatSessions
        CHAT_HANDLER_NAME: !GetAtt FilmChatFlowFunction.FunctionName

Resources:
  # DynamoDB テーブル
  SessionsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: filmate-sessions
      PrimaryKey:
        Name: sessionId
        Type: String

  # HTTP API をまとめる
  FilmateApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: prod

  # /filmChatEntry 用 Lambda
  FilmChatEntryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/filmChatEntry/
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - SecretsManagerReadPolicy:
            SecretId: !Ref SLACK_SECRET_ID
        - Statement:
            Effect: Allow
            Action: lambda:InvokeFunction
            Resource: !GetAtt FilmChatFlowFunction.Arn
      Events:
        FilmChatEntry:
          Type: HttpApi
          Properties:
            ApiId: !Ref FilmateApi
            Path: /filmChatEntry
            Method: POST
        FilmEvents:
          Type: HttpApi
          Properties:
            ApiId: !Ref FilmateApi
            Path: /events
            Method: POST

  # 会話フロー処理 Lambda
  FilmChatFlowFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/filmChatFlow/
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref SessionsTable
        - SecretsManagerReadPolicy:
            SecretId: !Ref SLACK_SECRET_ID

  # Slack イベント受信用 Lambda
  EventsHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/eventsHandler/
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
        - SecretsManagerReadPolicy:
            SecretId: !Ref SLACK_SECRET_ID
      Events:
        SlackEvents:
          Type: HttpApi
          Properties:
            ApiId: !Ref FilmateApi
            Path: /events
            Method: POST

Outputs:
  HttpApiUrl:
    Description: "Bot の HTTP API エンドポイント"
    Value: !Sub "https://${FilmateApi}.execute-api.${AWS::Region}.amazonaws.com"